### ISSUE TITLE
Module artifact resolution/transfer fails with KeyException

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow-admin-yarn#12]
Built and started with latest code from master. Getting exception creating `ticktock` stream on both `time` and `hdfs` modules - org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.springframework.cloud.stream.module:time-source:jar:exec:1.0.0.BUILD-SNAPSHOT from/to repository 1 (https://repo.spring.io/libs-snapshot): java.security.ProviderException: java.security.KeyException.

Full stacktrace:

```
2015-12-04 19:28:16,903 INFO [DefaultYarnContainer] [main] - Processing 1 @YarnComponent handlers
2015-12-04 19:28:16,922 INFO [ContainerApplication] [main] - runModule module=org.springframework.cloud.stream.module:hdfs-sink:jar:exec:1.0.0.BUILD-SNAPSHOT
2015-12-04 19:28:16,922 INFO [ContainerApplication] [main] - runModule properties={directory=/tmp/test, spring.cloud.stream.bindings.input.destination=ticktock.0, rollover=100, containerModules=org.springframework.cloud.stream.module:hdfs-sink:jar:exec:1.0.0.BUILD-SNAPSHOT}
2015-12-04 19:28:16,922 INFO [ContainerApplication] [main] - moduleLauncher=org.springframework.cloud.stream.module.launcher.ModuleLauncher@f2dc2d8
2015-12-04 19:28:16,922 INFO [ContainerApplication] [main] - Passing args to moduleLauncher: {spring.cloud.stream.bindings.input.destination=ticktock.0, directory=/tmp/test, rollover=100}
2015-12-04 19:28:17,776 INFO [DefaultYarnContainer] [main] - About to notifyEndState from catched exception
org.apache.hadoop.yarn.exceptions.YarnRuntimeException: Error processing container
    at org.springframework.yarn.container.MethodInvokingYarnContainerRuntimeProcessor.process(MethodInvokingYarnContainerRuntimeProcessor.java:53)
    at org.springframework.yarn.container.ContainerHandler.handle(ContainerHandler.java:99)
    at org.springframework.yarn.container.DefaultYarnContainer.getContainerHandlerResults(DefaultYarnContainer.java:174)
    at org.springframework.yarn.container.DefaultYarnContainer.runInternal(DefaultYarnContainer.java:77)
    at org.springframework.yarn.container.AbstractYarnContainer.run(AbstractYarnContainer.java:55)
    at org.springframework.yarn.boot.support.ContainerLauncherRunner.launchContainer(ContainerLauncherRunner.java:95)
    at org.springframework.yarn.boot.support.ContainerLauncherRunner.run(ContainerLauncherRunner.java:62)
    at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:794)
    at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:778)
    at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:765)
    at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:356)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:295)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1114)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1103)
    at org.springframework.cloud.dataflow.yarn.container.ContainerApplication.main(ContainerApplication.java:91)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.springframework.cloud.stream.module:hdfs-sink:jar:exec:1.0.0.BUILD-SNAPSHOT from/to repository 1 (https://repo.spring.io/libs-snapshot): java.security.ProviderException: java.security.KeyException
    at org.springframework.cloud.stream.module.resolver.AetherModuleResolver.resolve(AetherModuleResolver.java:191)
    at org.springframework.cloud.stream.module.resolver.AetherModuleResolver.resolve(AetherModuleResolver.java:125)
    at org.springframework.cloud.stream.module.launcher.ModuleLauncher.resolveModule(ModuleLauncher.java:264)
    at org.springframework.cloud.stream.module.launcher.ModuleLauncher.launchModule(ModuleLauncher.java:236)
    at org.springframework.cloud.stream.module.launcher.ModuleLauncher.launchIndividualModules(ModuleLauncher.java:229)
    at org.springframework.cloud.stream.module.launcher.ModuleLauncher.launch(ModuleLauncher.java:100)
    at org.springframework.cloud.stream.module.launcher.ModuleLauncher.launch(ModuleLauncher.java:108)
    at org.springframework.cloud.stream.module.launcher.ModuleLauncher.launch(ModuleLauncher.java:112)
    at org.springframework.cloud.dataflow.yarn.container.ContainerApplication.runModule(ContainerApplication.java:86)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.springframework.expression.spel.support.ReflectiveMethodExecutor.execute(ReflectiveMethodExecutor.java:113)
    at org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:129)
    at org.springframework.expression.spel.ast.MethodReference.access$000(MethodReference.java:49)
    at org.springframework.expression.spel.ast.MethodReference$MethodValueRef.getValue(MethodReference.java:342)
    at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:88)
    at org.springframework.expression.spel.ast.SpelNodeImpl.getTypedValue(SpelNodeImpl.java:131)
    at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:330)
    at org.springframework.yarn.support.AbstractExpressionEvaluator.evaluateExpression(AbstractExpressionEvaluator.java:126)
    at org.springframework.yarn.container.ContainerMethodInvokerHelper.processInternal(ContainerMethodInvokerHelper.java:229)
    at org.springframework.yarn.container.ContainerMethodInvokerHelper.process(ContainerMethodInvokerHelper.java:115)
    at org.springframework.yarn.container.MethodInvokingYarnContainerRuntimeProcessor.process(MethodInvokingYarnContainerRuntimeProcessor.java:51)
    ... 20 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.springframework.cloud.stream.module:hdfs-sink:jar:exec:1.0.0.BUILD-SNAPSHOT from/to repository 1 (https://repo.spring.io/libs-snapshot): java.security.ProviderException: java.security.KeyException
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
    at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294)
    at org.springframework.cloud.stream.module.resolver.AetherModuleResolver.resolve(AetherModuleResolver.java:187)
    ... 43 more
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.springframework.cloud.stream.module:hdfs-sink:jar:exec:1.0.0.BUILD-SNAPSHOT from/to repository 1 (https://repo.spring.io/libs-snapshot): java.security.ProviderException: java.security.KeyException
    at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:43)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
    at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
    ... 47 more
Caused by: javax.net.ssl.SSLException: java.security.ProviderException: java.security.KeyException
    at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
    at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1916)
    at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1874)
    at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1857)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1378)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1355)
    at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:543)
    at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:409)
    at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
    at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
    at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
    at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:882)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
    at org.apache.http.impl.client.DecompressingHttpClient.execute(DecompressingHttpClient.java:158)
    at org.eclipse.aether.transport.http.HttpTransporter.execute(HttpTransporter.java:287)
    at org.eclipse.aether.transport.http.HttpTransporter.implGet(HttpTransporter.java:243)
    at org.eclipse.aether.spi.connector.transport.AbstractTransporter.get(AbstractTransporter.java:59)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:447)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350)
    ... 52 more
Caused by: java.security.ProviderException: java.security.KeyException
    at sun.security.ec.ECKeyPairGenerator.generateKeyPair(ECKeyPairGenerator.java:146)
    at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:704)
    at sun.security.ssl.ECDHCrypt.<init>(ECDHCrypt.java:78)
    at sun.security.ssl.ClientHandshaker.serverKeyExchange(ClientHandshaker.java:714)
    at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:278)
    at sun.security.ssl.Handshaker.processLoop(Handshaker.java:913)
    at sun.security.ssl.Handshaker.process_record(Handshaker.java:849)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1035)
    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1344)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1371)
    ... 68 more
Caused by: java.security.KeyException
    at sun.security.ec.ECKeyPairGenerator.generateECKeyPair(Native Method)
    at sun.security.ec.ECKeyPairGenerator.generateKeyPair(ECKeyPairGenerator.java:126)
    ... 77 more
2015-12-04 19:28:17,780 INFO [DefaultYarnContainer] [main] - Container state based on method results=[] runtimeException=[org.apache.hadoop.yarn.exceptions.YarnRuntimeException: Error processing container]
2015-12-04 19:28:17,781 INFO [AbstractYarnContainer] [main] - Notifying listeners of ContainerState=FAILED and exit=org.apache.hadoop.yarn.exceptions.YarnRuntimeException: Error processing container
2015-12-04 19:28:17,781 DEBUG [ContainerLauncherRunner$1] [main] - Got state ContainerState=FAILED and exit=org.apache.hadoop.yarn.exceptions.YarnRuntimeException: Error processing container
2015-12-04 19:28:17,781 INFO [ContainerLauncherRunner] [main] - YarnContainer complete
2015-12-04 19:28:17,781 INFO [ContainerLauncherRunner] [main] - Exiting with exitCode=0
```

**Comment by trisberg** [comment]
This is due to an issue with OpenJDK 1.7.0 and RedHat/CentOS `nss` package. If I upgrade this package to a newer version with `yum update nss` then all is fine.

See http://blog.backslasher.net/java-ssl-crash.html for some nice troubleshooting tips regarding this issue.
