### ISSUE TITLE
Re-enable YarnStreamModuleDeployerIT tests once underlying issue is resolved

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow-admin-yarn#21]
We had to disable YarnStreamModuleDeployerIT tests since they were failing regularly due to some issue with the deployer. Once that is resolved we should re-enable these these tests.

**Comment by jvalkeal** [comment]
Re-enabled those tests and CI looks to be happy.

**Comment by trisberg** [comment]
I now see these errors again :(

```
Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 375.916 sec <<< FAILURE! - in org.springframework.cloud.dataflow.yarn.buildtests.YarnStreamModuleDeployerIT
testStreamTimeHdfs(org.springframework.cloud.dataflow.yarn.buildtests.YarnStreamModuleDeployerIT)  Time elapsed: 186.411 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: not null
     but: was null
    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
    at org.junit.Assert.assertThat(Assert.java:956)
    at org.junit.Assert.assertThat(Assert.java:923)
    at org.springframework.cloud.dataflow.yarn.buildtests.AbstractCliBootYarnClusterTests.assertWaitFileContent(AbstractCliBootYarnClusterTests.java:228)
    at org.springframework.cloud.dataflow.yarn.buildtests.YarnStreamModuleDeployerIT.testStreamTimeHdfs(YarnStreamModuleDeployerIT.java:198)

testStreamTimeLog(org.springframework.cloud.dataflow.yarn.buildtests.YarnStreamModuleDeployerIT)  Time elapsed: 183.563 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: not null
     but: was null
    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
    at org.junit.Assert.assertThat(Assert.java:956)
    at org.junit.Assert.assertThat(Assert.java:923)
    at org.springframework.cloud.dataflow.yarn.buildtests.AbstractCliBootYarnClusterTests.assertWaitFileContent(AbstractCliBootYarnClusterTests.java:228)
    at org.springframework.cloud.dataflow.yarn.buildtests.YarnStreamModuleDeployerIT.testStreamTimeLog(YarnStreamModuleDeployerIT.java:131)
```

**Comment by trisberg** [comment]
Plus, these mini-cluster tests leave a bunch of processes running on my Mac;

```
$ ps -ef | grep dataflow
  502  7930     1   0  9:53AM ttys000    0:20.64 /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin/java -jar spring-cloud-dataflow-yarn-streamappmaster-1.0.0.BUILD-SNAPSHOT.jar
  502  7978     1   0  9:53AM ttys000    0:33.29 /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin/java -Dserver.port=0 -Dendpoints.jmx.unique-names=true -Dspring.config.location=servers.yml -jar spring-cloud-dataflow-yarn-streamcontainer-1.0.0.BUILD-SNAPSHOT.jar containerModules=org.springframework.cloud.stream.module:log-sink:jar:exec:1.0.0.M2 spring.cloud.stream.bindings.input.destination=ticktock.0
  502  8009     1   0  9:53AM ttys000    0:31.76 /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin/java -Dserver.port=0 -Dendpoints.jmx.unique-names=true -Dspring.config.location=servers.yml -jar spring-cloud-dataflow-yarn-streamcontainer-1.0.0.BUILD-SNAPSHOT.jar containerModules=org.springframework.cloud.stream.module:time-source:jar:exec:1.0.0.M2 spring.cloud.stream.bindings.output.destination=ticktock.0
  502  8110     1   0  9:54AM ttys000    0:19.58 /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin/java -jar spring-cloud-dataflow-yarn-streamappmaster-1.0.0.BUILD-SNAPSHOT.jar
  502  8157     1   0  9:54AM ttys000    0:42.48 /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin/java -Dserver.port=0 -Dendpoints.jmx.unique-names=true -Dspring.config.location=servers.yml -jar spring-cloud-dataflow-yarn-streamcontainer-1.0.0.BUILD-SNAPSHOT.jar containerModules=org.springframework.cloud.stream.module:hdfs-sink:jar:exec:1.0.0.M2 spring.cloud.stream.bindings.input.destination=ticktock.0
  502  8191     1   0  9:55AM ttys000    0:33.30 /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin/java -Dserver.port=0 -Dendpoints.jmx.unique-names=true -Dspring.config.location=servers.yml -jar spring-cloud-dataflow-yarn-streamcontainer-1.0.0.BUILD-SNAPSHOT.jar containerModules=org.springframework.cloud.stream.module:time-source:jar:exec:1.0.0.M2 spring.cloud.stream.bindings.output.destination=ticktock.0
  502  8289     1   0  9:55AM ttys000    0:21.27 /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin/java -jar spring-cloud-dataflow-yarn-streamappmaster-1.0.0.BUILD-SNAPSHOT.jar
  502  8336     1   0  9:55AM ttys000    0:31.36 /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin/java -Dserver.port=0 -Dendpoints.jmx.unique-names=true -Dspring.config.location=servers.yml -jar spring-cloud-dataflow-yarn-streamcontainer-1.0.0.BUILD-SNAPSHOT.jar containerModules=org.springframework.cloud.stream.module:time-source:jar:exec:1.0.0.M2 spring.cloud.stream.bindings.output=timehdfs.0
  502  8367     1   0  9:56AM ttys000    0:44.46 /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin/java -Dserver.port=0 -Dendpoints.jmx.unique-names=true -Dspring.config.location=servers.yml -jar spring-cloud-dataflow-yarn-streamcontainer-1.0.0.BUILD-SNAPSHOT.jar containerModules=org.springframework.cloud.stream.module:hdfs-sink:jar:exec:1.0.0.M2 spring.cloud.stream.bindings.input=timehdfs.0 spring.hadoop.fsUri=hdfs://localhost:51185
  502  8584     1   0  9:58AM ttys000    0:19.72 /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin/java -jar spring-cloud-dataflow-yarn-streamappmaster-1.0.0.BUILD-SNAPSHOT.jar
  502  8635     1   0  9:59AM ttys000    0:30.11 /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin/java -Dserver.port=0 -Dendpoints.jmx.unique-names=true -Dspring.config.location=servers.yml -jar spring-cloud-dataflow-yarn-streamcontainer-1.0.0.BUILD-SNAPSHOT.jar containerModules=org.springframework.cloud.stream.module:time-source:jar:exec:1.0.0.M2 spring.cloud.stream.bindings.output=ticktock.0
  502  8673     1   0  9:59AM ttys000    0:34.23 /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin/java -Dserver.port=0 -Dendpoints.jmx.unique-names=true -Dspring.config.location=servers.yml -jar spring-cloud-dataflow-yarn-streamcontainer-1.0.0.BUILD-SNAPSHOT.jar containerModules=org.springframework.cloud.stream.module:log-sink:jar:exec:1.0.0.M2 spring.cloud.stream.bindings.input=ticktock.0 expression=new String(payload + ' hello')
```

**Comment by jvalkeal** [comment]
didn't u say that on mac yarn can't kill any processes. I can't reprod and CI is happy.

**Comment by trisberg** [comment]
I see the same failures on my Linux box. Did we change anything to fix this issue?

**Comment by jvalkeal** [comment]
new state machine version fixed some minor possible issues.

**Comment by trisberg** [comment]
I was able to reproduce this using Vagrant (attaching the Vagrant file):

```
vagrant up
vagrant ssh
$ git clone https://github.com/spring-cloud/spring-cloud-dataflow-admin-yarn.git
$ cd spring-cloud-dataflow-admin-yarn/
$ ./mvnw clean package
```

**Comment by trisberg** [comment]
[Vagrantfile.zip](https://github.com/spring-cloud/spring-cloud-dataflow-admin-yarn/files/80152/Vagrantfile.zip)

**Comment by jvalkeal** [comment]
It's something else because build was fine when I tried it via that vagrant.

**Comment by trisberg** [comment]
Not sure what to look for, either way I can't run the tests on any of my machines.

**Comment by jvalkeal** [comment]
I'll try to do a branch(disable most tests) so that we get all the logs from yarn.
