### ISSUE TITLE
Stream undeploy may fail

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow-admin-yarn#50]
Looks to be concurrency issues between controller and SPI usage:

```
org.springframework.yarn.boot.app.YarnContainerClusterClientException: Error communicating with rest endpoint; nested exception is org.springframework.web.client.HttpClientErrorException: 404 Not Found
    at org.springframework.yarn.boot.app.YarnContainerClusterTemplate.convertException(YarnContainerClusterTemplate.java:137) ~[spring-yarn-boot-2.4.0.BUILD-SNAPSHOT.jar!/:2.4.0.BUILD-SNAPSHOT]
    at org.springframework.yarn.boot.app.YarnContainerClusterTemplate.clusterInfo(YarnContainerClusterTemplate.java:85) ~[spring-yarn-boot-2.4.0.BUILD-SNAPSHOT.jar!/:2.4.0.BUILD-SNAPSHOT]
    at org.springframework.cloud.dataflow.module.deployer.yarn.YarnCloudAppServiceApplication.getClusterInfo(YarnCloudAppServiceApplication.java:199) ~[spring-cloud-dataflow-admin-yarn-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.cloud.dataflow.module.deployer.yarn.DefaultYarnCloudAppService.getInstanceClustersStates(DefaultYarnCloudAppService.java:169) ~[spring-cloud-dataflow-admin-yarn-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.cloud.dataflow.module.deployer.yarn.DefaultYarnCloudAppService.getClustersStates(DefaultYarnCloudAppService.java:149) ~[spring-cloud-dataflow-admin-yarn-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.cloud.dataflow.module.deployer.yarn.YarnStreamModuleDeployer.status(YarnStreamModuleDeployer.java:124) ~[spring-cloud-dataflow-admin-yarn-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.cloud.dataflow.module.deployer.yarn.YarnStreamModuleDeployer.status(YarnStreamModuleDeployer.java:111) ~[spring-cloud-dataflow-admin-yarn-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.cloud.dataflow.admin.controller.StreamDeploymentController.undeployStream(StreamDeploymentController.java:370) ~[spring-cloud-dataflow-admin-starter-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
```

**Comment by jvalkeal** [comment]
It looks like this bug is going to get fixed pretty much automatically with a new `AppDeployer` SPI. This was always a side effect of current SPI which never worked that good in a conceptual level.

**Comment by jvalkeal** [comment]
Marking invalid and closing as done with other fixes in https://github.com/spring-cloud/spring-cloud-yarn-deployer/issues/2.
